module.exports = [
    "editor-devtools",
    "block-switching",
    "editor-searchable-dropdowns",
    "color-picker",
    "data-category-tweaks-v2",
    "mediarecorder",
    "onion-skinning",
    "editor-stage-left",
    "remove-sprite-confirm",
    "bitmap-copy",
    "editor-theme3",
    "hide-flyout",
    "fix-uploaded-svgs",
];
